name: My Mastodon Digest 
on:
  schedule:
    - cron: '55 2,6,10,14,18 * * *'
  workflow_dispatch:
jobs:
  update:
    name: digest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: python things
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run digest
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
          MASTODON_USERNAME: ${{ secrets.MASTODON_USERNAME }}
        run: |
          python run.py -n 4 -s SimpleWeighted -t lax
      - name: publish
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: render
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
